### PR TITLE
Steam 848/svg render

### PR DESCRIPTION
**Pull request by Dtphelan1**
# Description
Issue: STEAM-848

Adapts the mCODE SVG visualization into a series of JSX Components. 

## Important Changes

This PR modifies the original SVG in several important ways necessary for working in a React application, including: 

- Kebab case translated into CamelCase for SVG properties (e.g. stroke-width becomes strokeWidth)
- Irrelevant SVG metadata removed
- Style Strings turned into Style Objects using more one-off regexes than anyone should ever have to create.
- SVG divs with links translated into anchor tags with hrefs
- Monolithic SVG divided into separate files, with helpful comments throughout
- [Unrelated] Added some folders to provide structure to `src` repo. 

Outstanding issues include the fact that several links were to relative URLs, not static ones. Those URLs will need to be translated into static URLs in order to work; this issue has been captured as STEAM-857.

## Testing Recommendations
Please list any recommendations regarding what reviewers should test and if there is any specific guidance on how to test certain aspects of the PR. Be sure to mention edge cases that should be tried, particularly in the UI.

- Ensure that there isn't any missing content based on [the original SVG](https://raw.githubusercontent.com/HL7/fhir-mCODE-ig/master/input/images/mCodeDiagram.svg).
- Ensure that each section contains all and exclusively relevant SVG components (you can accomplish this by removing each section at a time and checking that it still renders).

# Checklists

**Submitter:**
- [x] This PR describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] This PR includes the correct GH issue reference.
- [x] Comment added to the relevant GH issue(s) with a link to this PR
- [x] Code diff has been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)

@ACCT1 :
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code
- [ ] If applicable, you have considered possible performance regressions
- [ ] Tested all recommendations listed in the "Testing Recommendations" section. The application behaves as expected with this PR.

### CODE REVIEW

**Review by dmendelowitz — CHANGES_REQUESTED** [review]
This looks really good! The only issue I noticed is that it looks like the line segment goes over the "Component" under both "Genomic Variant" and "Genomic Region Studied" blocking the "p".
svg_error

**Comment by Dtphelan1** [comment]
A great finer-point Dylan. This has been addressed in three sections now 😄

**Comment by dmendelowitz** [comment]
The most recent commit doesn't seem to have changed anything for me. Tested on both Chrome and Edge in case it was a browser thing, same on both. Still looks like my screenshot above, does it look fixed for you?

**Comment by Dtphelan1** [comment]
I promise I'm not making it up, it looks good on my machine 
image

**Comment by Dtphelan1** [comment]
oh. I missed the second part of your comment....

Hold

**Comment by Dtphelan1** [comment]
Deleted my shameful misunderstanding of your original request. I have now fixed the Component bubble... let's forget this ever happened.......

**Review by dmendelowitz — APPROVED** [review]

**Pull request merged**
