### PR TITLE
Longitudinal Section

### PR DESCRIPTION
**Pull request by AldenB0**
# Description
Issue: STEAM-1061

I created a section component to house the linechart and the metrics data. Along with this I also moved the static data and the linechart function off of `app.js`.

## (Feature) Demo/Screenshots
image

## Important Changes
`LongitudinalSection.js`
- Created a div containing a title, time range dropdown, linechart, and an empty metrics component.

_General changes_

`app.js`
- Moved the static data and the linechart function to `LongitudinalSection.js` to keep things cleaner. 

`metrics.js`
-Brought into existence.

# Checklists

**Submitter:**
- [x] This PR describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] This PR includes the correct JIRA issue reference.
- [x] Code diff has been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)

@ACCT1 :
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] You have tried to break the code
- [ ] Tested all recommendations listed in the "Testing Recommendations" section. The application behaves as expected with this PR.

### CODE REVIEW

**Review by Dtphelan1 — CHANGES_REQUESTED** [review]
So for this task, we want a component that showcases more dynamic functionality. You can look over at [Dylan's current PR](https://github.com/mcode/mcode-coverage-checker/pull/33) for a better idea of how this is accomplished, but a few things we want to do. 
- Change the title of the visualization based on which section is currently selected.
- Change the styling of the title based on which section is currently selected.
- Render two instances of the Metrics component and probably align them how they are in the mockups. Obviously don't worry about any actual rendering of metrics, but maybe have some placeholder text and align that accordingly 
- We should be passing the CoverageData to the Section component. We shouldn't worry reformatting/rendering it on the chart right now, since it goes outside the scope of our current 3-points, but the data should be passed at least.

**Comment by AldenB0** [comment]
> So for this task, we want a component that showcases more dynamic functionality. You can look over at [Dylan's current PR](https://github.com/mcode/mcode-coverage-checker/pull/33) for a better idea of how this is accomplished, but a few things we want to do.
> 
>     * Change the title of the visualization based on which section is currently selected.
> 
>     * Change the styling of the title based on which section is currently selected.
> 
>     * Render two instances of the Metrics component and probably align them how they are in the mockups. Obviously don't worry about any actual rendering of metrics, but maybe have some placeholder text and align that accordingly
> 
>     * We should be passing the CoverageData to the Section component. We shouldn't worry reformatting/rendering it on the chart right now, since it goes outside the scope of our current 3-points, but the data should be passed at least.

Sounds good, and thanks for the clarification. I'll get on those additional features as soon as possible.

**Comment by AldenB0** [comment]
Just for clarification the last change I made was just a rebase since I will be using some aspects of Dylan M's code.

**Review by Dtphelan1 — APPROVED** [review]

**Comment by Dtphelan1** [comment]
This looks great!

**Pull request merged**
